name: artifacts-render
on:
  workflow_dispatch:
    inputs:
      name: 'Person to greet'
      required: true
      default: 'World'
jobs:
  create-artifacts:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
         echo "Hello ${{ github.event.inputs.name }}!" >> output.log
      - name: Upload output file
        uses: actions/upload-artifact@v1
        with:
          name: output-log-file
          path: output.log
