name: artifacts-render
on:
  workflow_dispatch:
    inputs:
      name: 'Person to greet'
      required: true
      default: 'World'
jobs:
  example-job:
    runs-on: ubuntu-latest
    name: Save output
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v1
        with:
          name: output-log-file
          path: output.log
